### ISSUE TITLE
Onkyo status 

### ISSUE THREAD

**Issue by Hochiss** [solowalker27/homebridge-onkyo#6]
Thanks again for your effort implemented _platform_! Great!

But Onkyo & its Volume not reflect real status. I have a smart plug controls TV and Onkyo, 
- while the plug is off, homebridge keep on log errors:
` [Onkyo] eventError: ERROR (server_error) Server error on xxx:xxx - Error: connect EHOSTUNREACH xxx:xxx` 
  would be nice to (like my Samsung TV) show as _off_  and stop error log; 
- Within iPhone Home, "Onkyo" is grey but its "Volume" is light up, which should also be grey(=off); In fact, "Volume" seems always light-up? 
- would it be possible to use MAC only instead of IP address, because its DHCP could assign a new IP, which makes onkyo not reachable.

![Screen Shot 2019-08-31 at 07 43 19](https://user-images.githubusercontent.com/36304198/64059772-30d77a80-cbc3-11e9-8a72-43a21ed4abc5.png)

**Comment by solowalker27** [comment]
Sorry for the late reply.

That error wouldn't be coming from my code. Looks like that's from the `eiscp` package that's actually handling the connection to your receiver. I don't know for sure but my guess is maybe your receiver isn't set up to go standby when you power it "off"; or maybe it's not set to allow network connections when in standby. Something like that.

If you're using the Volume "dimmer", it only reflects the volume state. On/off is for mute and the "brightness" is the volume. I can take your feedback as a feature request to see if there's a way I could sync the power status with the volume dimmer and also set the dimmer to off when the receiver is off. Not sure that would be a trivial change, though.

Now that this is a platform, it's theoretically possible to not use the IP address and to try to do something else like the MAC address instead. The eiscp package has some automatic discovery features that I could try to use. I kinda have been planning on doing that but haven't gotten there yet.

**Comment by Hochiss** [comment]
Thanks again for taking time to create this great plugin, I really like it and pretty sure a lot fans! (thanks also to @toshibochan for introduce me here. 

But this plugins has always not so stable for me, e.g. like above errors. I have my Samsung TV and TX-NR636 both connected ethernet via a router, which all of them share one power multi-plug, so that I can switch off all AVR devices with one ON/OFF. Samsung TV has always working fine via Homekit or the AppleTV-like remote control on iPhone, but not Onkyo TX-NR636. Yes, once it works, I can ON/OF, adjust volume and switch HDMI/inputs etc. But mostly it is not, also the status... ( just now, even the IP is correct, no reaction from Homekit, HB status(green)  shows (in red):
`[Onkyo] eventError: ERROR (arg_not_in_range) Command master-volume=100 is not available on this model. `

On the other side, really appreciate if you join hand with [Todd](https://github.com/ToddGreenfield/homebridge-onkyo) or launch your NPM, so that, more people could know you and benefit from the _platform_implementation.

**Comment by solowalker27** [comment]
Did you check into your receiver settings like I mentioned last time to ensure your receiver is setup to accept connections in standby mode? Also, if you continue to have your IP address change, you could consider creating a reservation for it on your router so it always gets the same IP address and you never have to worry about that again.

In the latest version I attempted to sync the volume dimmer on/off with the main power on/off. Not sure how well it worked, though. If it means that much to you you can set an Automation up that does it. Create one that turns off the volume dimmer when the receiver TV accessory is turned off, then another one where the volume dimmer turns on when it’s on. That should solve that problem for you.

As for the the latest error, your model’s volume must not go up to 100. For that, in your config you should set a `max_volume` for whatever your receiver’s volume limit is (it whatever the maximum you’d ever put it up to without blowing your ears or your speakers), and then set `map_volume_100`. That way when you’re using the volume dimmer 100% will be whatever your max volume is (e.g. 60) instead of 100.

You’d have to be more specific about any other stability issues you’re having to see if I can help solve them.

**Comment by toshibochan** [comment]
This is my config 

               "platform": "Onkyo",
                "name": "Onkyo",
                "receivers": [{
                        "model": "TX-NR636",
                        "ip_address": "10.0.1.14",
                        "poll_status_interval": "3000",
                        "max_volume": "100",
                        "map_volume_100": true,
                        "name": "Receiver",
                        "inputs": {
                                "dvd": "APTV 4K",
                                "video2": "APTV JP",
                                "video6": "APTV Office",
                                "video3": "FireTV"
                        },
                        "volume_dimmer": true,
                        "switch_service": false,
                        "filter_inputs": true

**Comment by solowalker27** [comment]
Hopefully you got this figured out. If not, feel free to reopen or create a new issue.

**Comment by Hochiss** [comment]
> Sorry for the late reply.
> 
> That error wouldn't be coming from my code. Looks like that's from the `eiscp` package that's actually handling the connection to your receiver. I don't know for sure but my guess is maybe your receiver isn't set up to go standby when you power it "off"; or maybe it's not set to allow network connections when in standby. Something like that.
> 

problem still maintain, the problem is AVR is powered - off. For security reason, you cannot leave it in standby. mode. PS: I try both with LAN connection via 2nd router, or WiFi with main router.

Still the red error lines come, until I power on the AVR.

**Comment by solowalker27** [comment]
I'm not likely to be maintaining this anymore since it's been merged into the parent repo which has drifted quire a lot from my fork, plus I've upgraded my receiver and no longer have an Onkyo.

However, as mentioned before there's not likely anything I can do. If your receiver is all the way off and not in standby, I doubt there's going to be any way for you to contact it. Can you even use the Onkyo app to turn it on when it's off like that?

I can point you back to the main repo and suggest you try it, but once again, it's not likely to work due to how you're operating the AVR.
